DROP TABLE IF EXISTS SENTENCES;
DROP TABLE IF EXISTS OBJECTS;
DROP TABLE IF EXISTS PREPOSITIONS;
DROP TABLE IF EXISTS VERBS;

CREATE TABLE VERBS (
word VARCHAR(40) NOT NULL,
PRIMARY KEY (word)
);

CREATE TABLE PREPOSITIONS (
word VARCHAR(10) NOT NULL,
PRIMARY KEY (word)
);

CREATE TABLE OBJECTS (
word VARCHAR(40) NOT NULL,
PRIMARY KEY (word)
);

CREATE TABLE SENTENCES (
id INT NOT NULL,
verb VARCHAR(40) NOT NULL,
preposition VARCHAR(10),
objects VARCHAR(40),
PRIMARY KEY (id),
FOREIGN KEY (verb) REFERENCES VERBS(word),
FOREIGN KEY (preposition) REFERENCES PREPOSITIONS(word),
FOREIGN KEY (objects) REFERENCES OBJECTS(word)
);
