DROP TABLE IF EXISTS SENTENCES;
DROP TABLE IF EXISTS OBJECTS;
DROP TABLE IF EXISTS PREPOSITIONS;
DROP TABLE IF EXISTS VERBS;

CREATE TABLE VERBS (
word VARCHAR(40) NOT NULL,
PRIMARY KEY (word)
);

CREATE TABLE PREPOSITIONS (
word VARCHAR(10) NOT NULL,
PRIMARY KEY (word)
);

CREATE TABLE OBJECTS (
word VARCHAR(40) NOT NULL,
PRIMARY KEY (word)
);

CREATE TABLE SENTENCES (
id INT NOT NULL,
verb VARCHAR(40) NOT NULL,
preposition VARCHAR(10),
objects VARCHAR(40),
PRIMARY KEY (id),
FOREIGN KEY (verb) REFERENCES VERBS(word),
FOREIGN KEY (preposition) REFERENCES PREPOSITIONS(word),
FOREIGN KEY (objects) REFERENCES OBJECTS(word)
);


INSERT INTO VERBS VALUES ('look');
INSERT INTO VERBS VALUES ('eye');
INSERT INTO VERBS VALUES ('glance');
INSERT INTO VERBS VALUES ('glimpse');
INSERT INTO VERBS VALUES ('peek');
INSERT INTO VERBS VALUES ('view');
INSERT INTO VERBS VALUES ('gander');
INSERT INTO VERBS VALUES ('gaze');
INSERT INTO VERBS VALUES ('inspect');
INSERT INTO VERBS VALUES ('leer');
INSERT INTO VERBS VALUES ('observe');
INSERT INTO VERBS VALUES ('watch');

INSERT INTO VERBS VALUES ('move');
INSERT INTO VERBS VALUES ('go');
INSERT INTO VERBS VALUES ('walk');
INSERT INTO VERBS VALUES ('run');
INSERT INTO VERBS VALUES ('jog');
INSERT INTO VERBS VALUES ('tiptoe');
INSERT INTO VERBS VALUES ('stomp');
INSERT INTO VERBS VALUES ('shimmy');

INSERT INTO VERBS VALUES ('ask');
INSERT INTO VERBS VALUES ('inquire');
INSERT INTO VERBS VALUES ('question');


INSERT INTO PREPOSITIONS VALUES ('to');
INSERT INTO PREPOSITIONS VALUES ('at');
INSERT INTO PREPOSITIONS VALUES ('about');
INSERT INTO PREPOSITIONS VALUES ('for');
INSERT INTO PREPOSITIONS VALUES ('from');
INSERT INTO PREPOSITIONS VALUES ('');
INSERT INTO PREPOSITIONS VALUES ('');
INSERT INTO PREPOSITIONS VALUES ('');
INSERT INTO PREPOSITIONS VALUES ('');
INSERT INTO PREPOSITIONS VALUES ('');
INSERT INTO PREPOSITIONS VALUES ('');
INSERT INTO PREPOSITIONS VALUES ('');